# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 157.0.8097.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
  Custom: --chrome-sxs --do-not-launch-chrome
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Google Chrome
ReleaseDate: 2026-10-10
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/gzd7scqujdntabeupwna272sc4_157.0.8097.0/157.0.8097.0_chrome_installer_uncompressed.exe
  InstallerSha256: 4227BB29F64D826FAAA4E8EEC5A12237F1C8CE0B4D7548161CDC4B3576698376
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/p63ynkxobbgskxd4rxvgm2k35a_157.0.8097.0/157.0.8097.0_chrome_installer_uncompressed.exe
  InstallerSha256: A4464DFB282E0F23C70C8AEA998E6029249A157A352B4B462B0627630499E2C0
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/acaxaz233pmcl7drdobbcvklb5fa_157.0.8097.0/157.0.8097.0_chrome_installer_uncompressed.exe
  InstallerSha256: 4C55B0123C5A575F293F75F044CFA12D0543BB49643FC16F402DDB6C68DE3C0E
ManifestType: installer
ManifestVersion: 1.12.0
