# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: holland-built.Bloxsmith
PackageVersion: 3.92.12
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bloxsmith.exe
  PortableCommandAlias: bloxsmith
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/holland-built/bloxsmith/releases/download/v3.92.12/bloxsmith_3.92.12_windows_amd64.zip
  InstallerSha256: 5D8FDEBD8287C4875BAB1FDE927F88D3D6836C437E4EFE2609FA2F29FCC3D9F5
ManifestType: installer
ManifestVersion: 1.12.0
