# Automatically updated by the winget bot at 2026/Oct/10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: AOMEI.Backupper.Standard
PackageVersion: 8.5.0.0
InstallerType: inno
Scope: machine
Installers:
- Architecture: x86
  InstallerUrl: https://www2.aomeisoftware.com/download/adb/AOMEIBackupperStd.exe
  InstallerSha256: 4EC9445146641A8F5A5F48DD484372F1EE8CC8F19D4F15E41086D0DD6BC0621F
ManifestType: installer
ManifestVersion: 1.28.0
