# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AgentSeal.CodeBurnMenubar
PackageVersion: 0.9.26
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ProductCode: '{E0B48C02-ADC5-4C2A-BF56-629BCA19D3A8}'
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- UpgradeCode: '{CFE9191D-31EA-5040-83C8-CEFD2A10B703}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/getagentseal/codeburn/releases/download/windows-v0.9.26/CodeBurn.Menubar_0.9.26_x64_en-US.msi
  InstallerSha256: 325A10452CB35DAB37D70DDE6EA87733CBAA03A4B8DC1C0616747A0D40A1D304
ManifestType: installer
ManifestVersion: 1.12.0
