# Automatically updated by the winget bot at 2026/Oct/10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Elcomsoft.AdvancedPDFPasswordRecovery
PackageVersion: 5.20.198.8205
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{141F8340-15BB-429D-8DB8-CF5276587DF4}'
ReleaseDate: 2024-07-30
AppsAndFeaturesEntries:
- ProductCode: '{141F8340-15BB-429D-8DB8-CF5276587DF4}'
  UpgradeCode: '{47796195-6EFC-401E-BE95-7D44C5C16C1E}'
Installers:
- Architecture: x86
  InstallerUrl: https://www.elcomsoft.com/download/apdfpr_setup_en.msi
  InstallerSha256: 99994EA2A5F7E1D0E6D115A5CC78BD58DE9A37C355A37DCFC4EEE29692A1A1EB
ManifestType: installer
ManifestVersion: 1.28.0
