# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArtCraft.VectorCraft
PackageVersion: 0.9.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-11
AppsAndFeaturesEntries:
- UpgradeCode: '{601C6437-08AE-4645-ADCC-27F036C2EA2F}'
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/storytold/vectorcraft/releases/download/v0.9.0/vectorcraft-0.9.0-windows-x86.msi
  InstallerSha256: 1BBFC98CA33A045C4C5AC6AEF7C87D7E1A9A12DD1C6425761C4CC51658023917
  ProductCode: '{96F74991-6D91-4298-B0AF-35801678A8FE}'
- Architecture: x64
  InstallerUrl: https://github.com/storytold/vectorcraft/releases/download/v0.9.0/vectorcraft-0.9.0-windows-x64.msi
  InstallerSha256: DE590A69AC3345F32586EFA1B608F868C5CA71CDE5646AED715054C68DA73C23
  ProductCode: '{4A30A4CB-6249-4CC2-AE76-10F300388781}'
- Architecture: arm64
  InstallerUrl: https://github.com/storytold/vectorcraft/releases/download/v0.9.0/vectorcraft-0.9.0-windows-arm64.msi
  InstallerSha256: 481C2981EAFC6DE6A35295420EE7D8D65C65BF986B79E2AE272536AB8CA3274D
  ProductCode: '{7DB1848A-1002-457B-994D-EF5BA77B0316}'
ManifestType: installer
ManifestVersion: 1.12.0
