# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SerZhyAle.FileDO
PackageVersion: "2610102316"
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: filedo.exe
  PortableCommandAlias: filedo
- RelativeFilePath: filedo_check.exe
  PortableCommandAlias: filedo_check
- RelativeFilePath: filedo_fill.exe
  PortableCommandAlias: filedo_fill
- RelativeFilePath: filedo_test.exe
  PortableCommandAlias: filedo_test
- RelativeFilePath: filedo_win.exe
  PortableCommandAlias: filedo_win
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SerZhyAle/FileDO/releases/download/v2610102316/FileDO-2610102316-windows-x64.zip
  InstallerSha256: 5CAB78099409EC27A26EB21CB71E92074DF135B45CB69B08BD282FB20666784C
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-10
