# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Yaak.app
PackageVersion: 2026.9.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
ProductCode: Yaak
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- Publisher: Yaak
  ProductCode: Yaak
InstallationMetadata:
  DefaultInstallLocation: "%LocalAppData%\\Yaak"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mountain-loop/yaak/releases/download/v2026.9.0/Yaak_2026.9.0_x64-setup.exe
  InstallerSha256: AF45E72C91B86B9D005D477F9E87B03D4B7310001E26362ABF1F97418FA1D720
ManifestType: installer
ManifestVersion: 1.12.0
