# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sapryx.Nexora
PackageVersion: 0.3.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Nexora.exe
  PortableCommandAlias: nexora
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Sapryx/Nexora/releases/download/0.3.0/Nexora-win-x64.zip
  InstallerSha256: 0E76EF20EE5C137FB123D913BDF65FE8441D5D1CC9027E36973A3816EE0B3DFA
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-10
