# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: SST.OpenCodeDesktop
PackageVersion: 1.19.0
InstallerType: nullsoft
Scope: user
ProductCode: d074f30d-5f88-5885-b075-be1348cc7676
ReleaseDate: 2026-10-11
AppsAndFeaturesEntries:
- ProductCode: d074f30d-5f88-5885-b075-be1348cc7676
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\OpenCode'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.19.0/opencode-desktop-win-x64.exe
  InstallerSha256: 41C9429A265A7626B0EFC78764719F7B8D69F754720CB15C791ECA0594FEABD1
- Architecture: arm64
  InstallerUrl: https://github.com/anomalyco/opencode/releases/download/v1.19.0/opencode-desktop-win-arm64.exe
  InstallerSha256: 917E0666503EC570E99A3B3CD3E1F4F8C26799A4A23E703B29923CEFAFB61E4B
ManifestType: installer
ManifestVersion: 1.28.0
