# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.663.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-10-10
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.663.0&arch=x86
  InstallerSha256: B5849E32CFB3259D287894C6BA067A2CA4D559562D53B2869624DFFDF870D57A
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.663.0&arch=amd64
  InstallerSha256: ACCB29E232B52BDA0BB3E1D6569BF9BA3F59F559A4B36B89790E2CABA7B87A36
ManifestType: installer
ManifestVersion: 1.28.0
