# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: RocketChat.RocketChat
PackageVersion: 4.18.2
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: 9b73a9fb-f1d5-59ee-b41e-e1dd393a748a
ReleaseDate: 2026-10-11
AppsAndFeaturesEntries:
- ProductCode: 9b73a9fb-f1d5-59ee-b41e-e1dd393a748a
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.18.2/rocketchat-4.18.2-win-ia32.exe
  InstallerSha256: AD492CDAD3D7032AE8BC02CA900BCCF3C8FB4418B571F6F12BF61E433DC68AE8
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.18.2/rocketchat-4.18.2-win-ia32.exe
  InstallerSha256: AD492CDAD3D7032AE8BC02CA900BCCF3C8FB4418B571F6F12BF61E433DC68AE8
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.18.2/rocketchat-4.18.2-win-x64.exe
  InstallerSha256: 9D9EAE967EBFA3B3E077A88E06A640728D7956A840730E3A340940D490C4DE05
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.18.2/rocketchat-4.18.2-win-x64.exe
  InstallerSha256: 9D9EAE967EBFA3B3E077A88E06A640728D7956A840730E3A340940D490C4DE05
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.18.2/rocketchat-4.18.2-win-arm64.exe
  InstallerSha256: F2A55BACAE8908CE88B8FA8E9B19C25B05A02EE02DA8FD1FE93FBC20F43E9F13
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/4.18.2/rocketchat-4.18.2-win-arm64.exe
  InstallerSha256: F2A55BACAE8908CE88B8FA8E9B19C25B05A02EE02DA8FD1FE93FBC20F43E9F13
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.28.0
