# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: dprint.dprint
PackageVersion: 0.62.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dprint.exe
ReleaseDate: 2026-10-11
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dprint/dprint/releases/download/0.62.0/dprint-x86_64-pc-windows-msvc.zip
  InstallerSha256: 322E47E188BBA6FF3784EF1BE0C5F569FC270467EEAC4DD10015030599D9466D
- Architecture: arm64
  InstallerUrl: https://github.com/dprint/dprint/releases/download/0.62.0/dprint-aarch64-pc-windows-msvc.zip
  InstallerSha256: 39C70A48172840D7B40F1133FF4F944B2B5775E5B58CECD170FDCD43884AC415
ManifestType: installer
ManifestVersion: 1.28.0
