# Automatically updated by the winget bot at 2026/Oct/10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: GaoyangZhang.RivonClaw
PackageVersion: 1.9.28
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 51492edb-6d67-582c-a781-6b48bbf5f3bf
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.9.28/TK-Copilot.Setup.1.9.28.exe
  InstallerSha256: 38DE5C4A10CCFD95A4E64F61C385614C081B1B57C46B7E8BF6BC7146D8738347
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/gaoyangz77/rivonclaw/releases/download/v1.9.28/TK-Copilot.Setup.1.9.28.exe
  InstallerSha256: 38DE5C4A10CCFD95A4E64F61C385614C081B1B57C46B7E8BF6BC7146D8738347
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.28.0
