# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.320
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.320/anchors_0.1.320_windows_amd64.zip
  InstallerSha256: DFB4D91898DE40244910F9C0B9959E9C07DF9C454931C6AF0FC0552244244247
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.320/anchors_0.1.320_windows_arm64.zip
  InstallerSha256: 326F4C0F2E540CAC4274FA9A44AB65D0CF0EF3A007B15CF6219C8B951496991C
ManifestType: installer
ManifestVersion: 1.12.0
