# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sysmanage.sysmanage
PackageVersion: 3.10.0.7
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.10.0.7/sysmanage-3.10.0.7-windows-x64.msi
  InstallerSha256: BF705224A5D12984DDF4162E14EBB3AF19A88552930820BAD1CBFCD11B2F25CB
  ProductCode: '{F6D3FC2E-7E62-470D-B513-1C8024863AA6}'
  AppsAndFeaturesEntries:
  - ProductCode: '{F6D3FC2E-7E62-470D-B513-1C8024863AA6}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
- Architecture: arm64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.10.0.7/sysmanage-3.10.0.7-windows-arm64.msi
  InstallerSha256: 2029598BE26A046B6138A4189E31C150580288567C48F101BD2B353E122CEF44
  ProductCode: '{EF9F2CA5-5A06-461F-A0CF-508B431B639B}'
  AppsAndFeaturesEntries:
  - ProductCode: '{EF9F2CA5-5A06-461F-A0CF-508B431B639B}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
ManifestType: installer
ManifestVersion: 1.12.0
