# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PortSwigger.BurpSuite
PackageVersion: 2026.9.1
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -q -Dinstall4j.suppressUnattendedReboot=true
  SilentWithProgress: -q -splash "" -Dinstall4j.suppressUnattendedReboot=true
  InstallLocation: -dir "<INSTALLPATH>"
  Log: -Dinstall4j.log="<LOGPATH>"
UpgradeBehavior: install
FileExtensions:
- burp
ProductCode: 6592-1155-2163-3973
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.1&type=WindowsX64
  InstallerSha256: CEAC9A6931477D2335FBF124DFFDA6A519FB99DCC384113C34F170AD81DEBE9C
- Architecture: x64
  Scope: machine
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.1&type=WindowsX64
  InstallerSha256: CEAC9A6931477D2335FBF124DFFDA6A519FB99DCC384113C34F170AD81DEBE9C
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.1&type=WindowsArm64
  InstallerSha256: 4C80144EB36B245106B60B07F5C06648D11AA97EF93CF0E5297B203D52F85475
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://portswigger.net/burp/releases/download?product=desktop&version=2026.9.1&type=WindowsArm64
  InstallerSha256: 4C80144EB36B245106B60B07F5C06648D11AA97EF93CF0E5297B203D52F85475
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
