# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sysmanage.sysmanage
PackageVersion: 3.10.0.6
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.10.0.6/sysmanage-3.10.0.6-windows-x64.msi
  InstallerSha256: 327FB0B16F13794855F7BD5247E049154F185CCBC8AFAF7FE86EF491F33A77A1
  ProductCode: '{2CE96F8D-45E0-4BF7-A495-EDE4B181C1FD}'
  AppsAndFeaturesEntries:
  - ProductCode: '{2CE96F8D-45E0-4BF7-A495-EDE4B181C1FD}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
- Architecture: arm64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.10.0.6/sysmanage-3.10.0.6-windows-arm64.msi
  InstallerSha256: 6A0CBD4E0A28931B0A59B2A9F1937F082ED49E1A1B367F51185A9CCAD2981ACF
  ProductCode: '{E65A472D-1D94-4577-A80C-7BE217B2BD1D}'
  AppsAndFeaturesEntries:
  - ProductCode: '{E65A472D-1D94-4577-A80C-7BE217B2BD1D}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
ManifestType: installer
ManifestVersion: 1.12.0
