# Automatically updated by the winget bot at 2026/Oct/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: LMCP.LocalMCP
PackageVersion: 3.0.420
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Scope: machine
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://download.local-mcp.com/LMCP-Setup.exe
  InstallerSha256: 0910A97C1050FD3A6398BCF9E2EF046A3BBF3E50A4E9399D0048DF0A9B2D1F3F
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.28.0
