# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixCLI
PackageVersion: 2.35.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: reasonix.exe
Commands:
- reasonix
ReleaseDate: 2026-10-11
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v2.35.0/reasonix-windows-amd64.zip
  InstallerSha256: 9FEDCF1A6C1CB1660679137482B3D639DC0264EFBE972A9FDCE2079AF6E82FF4
- Architecture: arm64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v2.35.0/reasonix-windows-arm64.zip
  InstallerSha256: FAB9F32822D058D1BD5DC624E1925F11360C98A420955B8EEE53E8A3BF8389DE
ManifestType: installer
ManifestVersion: 1.12.0
