# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: PocketBase.PocketBase
PackageVersion: 0.40.5
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pocketbase.exe
  PortableCommandAlias: pocketbase
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pocketbase/pocketbase/releases/download/v0.40.5/pocketbase_0.40.5_windows_amd64.zip
  InstallerSha256: D0980D1F3A8097FF4C03A876E8C98F3008A83C0D42CC03B636BC92B2D4788D1C
- Architecture: arm64
  InstallerUrl: https://github.com/pocketbase/pocketbase/releases/download/v0.40.5/pocketbase_0.40.5_windows_arm64.zip
  InstallerSha256: 7DD0D7C500812CAC571E450525595B93556527161B1EB86493DABDFC31974EF5
ManifestType: installer
ManifestVersion: 1.12.0
