# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1791662459-g6be10b
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1791662459-g6be10b/amp-windows-x64-baseline.exe
  InstallerSha256: 79D5B0705D6B10F92A924C311583316ECB1DF1FB26CC0587894D6B7359D85DAD
ManifestType: installer
ManifestVersion: 1.12.0
