# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json
PackageIdentifier: TheRealJesusTheHacker.NitroCore
PackageVersion: 1.1.2
PackageLocale: en-US
Publisher: JesusTheHacker
PackageName: NitroCore
License: MIT
ShortDescription: Free Windows optimizer for gaming and cybersecurity workstations.
ManifestType: version
ManifestVersion: 1.10.0
DefaultLocale: en-US
