# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: TheRealJesusTheHacker.NitroCore
PackageVersion: 1.1.2
InstallerType: portable
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/TheRealJesusTheHacker/NitroCore/releases/download/v1.1.2/NitroCoreOptimizer.exe
  InstallerSha256: E265F14E91271958D4FEFE6DDC7E7E9ABEBAC6FD3DA0C525D870CE341F158A4E
ManifestType: installer
ManifestVersion: 1.10.0
